---
- name: Playbook from Variables
  hosts: prod_servers
  become: yes


  vars:
    message1: Hellow
    message2: World
    secret   : XCXCXCXCXC


  tasks:

  - name: Hellow secret Variables
    debug:
      var: secret


  - debug:
      msg: "Secret slovo: {{ secret }}"


  - debug:
      msg: "Owner This Server -->{{ owner }}<--"



  - set_fact: full_message="{{ message1 }} {{ message2 }} from {{ owner }}"

  - debug:
      var: full_message



  - debug:
      var: ansible_distribution



  - shell: uptime
    register: results

  - debug:
      var: results.stdout
  
